/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZReportImport } from './routes/z-report'
import { Route as XReportImport } from './routes/x-report'
import { Route as MenuboardImport } from './routes/menu_board'
import { Route as ManagerNavImport } from './routes/manager-nav'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZReportRoute = ZReportImport.update({
  id: '/z-report',
  path: '/z-report',
  getParentRoute: () => rootRoute,
} as any)

const XReportRoute = XReportImport.update({
  id: '/x-report',
  path: '/x-report',
  getParentRoute: () => rootRoute,
} as any)

const MenuboardRoute = MenuboardImport.update({
  id: '/menu_board',
  path: '/menu_board',
  getParentRoute: () => rootRoute,
} as any)

const ManagerNavRoute = ManagerNavImport.update({
  id: '/manager-nav',
  path: '/manager-nav',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/manager-nav': {
      id: '/manager-nav'
      path: '/manager-nav'
      fullPath: '/manager-nav'
      preLoaderRoute: typeof ManagerNavImport
      parentRoute: typeof rootRoute
    }
    '/menu_board': {
      id: '/menu_board'
      path: '/menu_board'
      fullPath: '/menu_board'
      preLoaderRoute: typeof MenuboardImport
      parentRoute: typeof rootRoute
    }
    '/x-report': {
      id: '/x-report'
      path: '/x-report'
      fullPath: '/x-report'
      preLoaderRoute: typeof XReportImport
      parentRoute: typeof rootRoute
    }
    '/z-report': {
      id: '/z-report'
      path: '/z-report'
      fullPath: '/z-report'
      preLoaderRoute: typeof ZReportImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/manager-nav': typeof ManagerNavRoute
  '/menu_board': typeof MenuboardRoute
  '/x-report': typeof XReportRoute
  '/z-report': typeof ZReportRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/manager-nav': typeof ManagerNavRoute
  '/menu_board': typeof MenuboardRoute
  '/x-report': typeof XReportRoute
  '/z-report': typeof ZReportRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/manager-nav': typeof ManagerNavRoute
  '/menu_board': typeof MenuboardRoute
  '/x-report': typeof XReportRoute
  '/z-report': typeof ZReportRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/manager-nav'
    | '/menu_board'
    | '/x-report'
    | '/z-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/manager-nav'
    | '/menu_board'
    | '/x-report'
    | '/z-report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/manager-nav'
    | '/menu_board'
    | '/x-report'
    | '/z-report'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ManagerNavRoute: typeof ManagerNavRoute
  MenuboardRoute: typeof MenuboardRoute
  XReportRoute: typeof XReportRoute
  ZReportRoute: typeof ZReportRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ManagerNavRoute: ManagerNavRoute,
  MenuboardRoute: MenuboardRoute,
  XReportRoute: XReportRoute,
  ZReportRoute: ZReportRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/manager-nav",
        "/menu_board",
        "/x-report",
        "/z-report"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/manager-nav": {
      "filePath": "manager-nav.tsx"
    },
    "/menu_board": {
      "filePath": "menu_board.tsx"
    },
    "/x-report": {
      "filePath": "x-report.tsx"
    },
    "/z-report": {
      "filePath": "z-report.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
